### ISSUE TITLE
Admin should be able to edit or delete any thread reply

### ISSUE THREAD

**Issue by daydevelops** [daydevelops/scallywags#17]

**Comment by bpotocnak96** [comment]
Hello, is it actual and opened?

**Comment by daydevelops** [comment]
Hi @bpotocnak96 yes this issue is open and you can feel free to work on it if you like.

**Comment by bpotocnak96** [comment]
Okey, I will work on it.

**Comment by daydevelops** [comment]
Thank you

**Comment by bpotocnak96** [comment]
I think that it is done, where I can put my solution?

**Comment by daydevelops** [comment]
Once you push your changes to your own repo you can create a pull request here so I can see what you have done
