### ISSUE TITLE
no indication that a thread is locked

### ISSUE THREAD

**Issue by daydevelops** [daydevelops/scallywags#5]
The admin of the site has the ability of locking a thread which prevents anyone from adding any more comments. 

Viewing a locked thread, you can see a message saying that the thread is locked. It would be nice if there was an indication of this on each thread without having to visit the thread. On the home page for example where multiple threads are listed.

**Comment by daydevelops** [comment]
yes @fifkis you can go ahead! thank you

**Comment by fifkis** [comment]
Sorry i find other issue where i working now.

**Comment by smolindamix** [comment]
Hello, can i work on it?
